version: '3.8'

services:
  mysql:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tfs
      MYSQL_USER: tfs
      MYSQL_PASSWORD: tfspass
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpass

  tfs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "7171:7171" # Client port
      - "7172:7172" # Game port
    volumes:
      - tfs_data:/srv
    depends_on:
      - mysql

volumes:
  mysql_data:
  tfs_data:
